### ISSUE TITLE
sorry dont know where to post

### ISSUE THREAD

**Issue by okatokat666** [Ashesh3/ROSUltraHack#7]
your invitation link for your discord has expired can you pls send a new one? also why am i removed from your discord? did i violate something? thank you.

**Comment by Ashesh3** [comment]
The Discord was taken down and there is no point of making a new one too, as it'll be taken down too.

**Comment by okatokat666** [comment]
okay thanks. i guess someone reported it. sorry to bother you. thank you again for your works.
